#!/bin/zsh
dirlist=("${(@f)$(cat ${GDC_WORK_DIR}/dir_list)}")
typeset -i len=${#dirlist[@]}
typeset -i n=1
typeset -i cparam=1
typeset -i nparam=1
typeset -i aparam=1

function print-all-dirs() {
  for i in {1..$len}
  do
    if [[ -n "${dirlist[i]}" ]]
    then
      printf "%-7d %s\n" $(( $len - $i )) ${dirlist[i]}
    fi
  done
}

function print-short-dirs() {
  i=$len
  en=1
  if [[ $len -gt $GDC_SHORT_DIRS ]]
  then
    en=$(( $len - $GDC_SHORT_DIRS + 1 ))
  fi

  while [[ $i -ge $en ]]
  do
    printf "%-7d %s\n" $(( $len - $i )) ${dirlist[i]}
    let i--
  done
}

while [[ -n "$1" ]]
do
  case "$1" in
    -c) if [[ -n "$2" ]]
    then
      if [[ $2 -ge 0 ]] && [[ $2 -lt $len ]]
      then
        n=$2
      fi
      shift
    fi
    cparam=0;;
    -n) if [[ -n "$2" ]]
    then
      if [[ $2 -ge 0 ]] && [[ $2 -lt $len ]]
      then
        n=$2
      fi
      shift
    fi
    nparam=0;;
    -a) aparam=0;;
  esac
  shift
done

typeset -i realn=$(( $len - $n ))

if [[ $cparam == 0 ]]; then
  if [[ -n "${dirlist[$realn]}" ]]; then
    cd ${dirlist[$realn]}
  fi
elif [[ $nparam == 0 ]]; then
  echo ${dirlist[$realn]}
elif [[ $aparam == 0 ]]; then
  print-all-dirs | less
else
  print-short-dirs
fi
